version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /examples/10-typescript-interop/ts_client
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /examples/10-typescript-interop/ts_server
    schedule:
      interval: monthly
